version: "3.8"

services:
  portainer:
    container_name: portainer_container
    image: portainer/portainer-ce:alpine
    restart: always
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_volume:/data

volumes:
  portainer_volume:
